"""Interactive CLI to create or update a .env file for Congress Trades.

Prompts for each API key / credential with descriptions, then writes
(or merges into an existing) .env file.  Existing values are preserved
unless the user explicitly replaces them.

Usage:
    uv run python scripts/setup_env.py
    uv run python scripts/setup_env.py --env-file /path/to/.env
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _load_existing_env(path: Path) -> dict[str, str]:
    """Parse an existing .env file into a {KEY: raw_value} dict.

    Handles quoted values and skips comments / blank lines.
    """
    env: dict[str, str] = {}
    if not path.exists():
        return env

    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip()
        # Strip surrounding quotes if present
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
            value = value[1:-1]
        env[key] = value

    return env


def _prompt(
    label: str,
    description: str,
    current: str = "",
    *,
    secret: bool = False,
    optional: bool = True,
) -> str:
    """Prompt the user for a value, showing the current value if one exists.

    Parameters
    ----------
    label:
        The environment variable name.
    description:
        Human-readable explanation shown before the prompt.
    current:
        The existing value (shown as placeholder, kept if user presses Enter).
    secret:
        If True, mask the displayed current value.
    optional:
        Whether to show "(optional)" hint.

    Returns
    -------
    str
        The new value (or the existing one if the user pressed Enter).
    """
    tag = " (optional)" if optional else " (required)"
    print(f"\n  {label}{tag}")
    print(f"  {description}")

    if current:
        masked = ("*" * min(len(current), 8) + current[-4:]) if secret else current
        print(f"  Current value: {masked}")
        prompt_str = "  New value [keep current]: "
    else:
        prompt_str = "  Value: "

    try:
        value = input(prompt_str).strip()
    except (EOFError, KeyboardInterrupt):
        print()
        return current

    return value if value else current


def _yes_no(question: str, default: bool = False) -> bool:
    """Prompt for a yes/no answer."""
    hint = "[Y/n]" if default else "[y/N]"
    try:
        answer = input(f"\n{question} {hint}: ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        print()
        return default

    if not answer:
        return default
    return answer in ("y", "yes")


def _write_env(path: Path, values: dict[str, str]) -> None:
    """Write the values dict to a .env file, one KEY=VALUE per line."""
    lines: list[str] = [
        "# Congress Trades — environment configuration",
        "# Generated by scripts/setup_env.py",
        "# Do NOT commit this file to version control.",
        "",
    ]

    sections: list[tuple[str, list[str]]] = [
        (
            "API Keys",
            ["ANTHROPIC_API_KEY", "ANTHROPIC_MODEL", "CONGRESS_API_KEY"],
        ),
        (
            "Telegram Alerts",
            ["TELEGRAM_BOT_TOKEN", "TELEGRAM_CHAT_ID"],
        ),
        (
            "Email / SMTP Alerts",
            [
                "ENABLE_EMAIL_ALERTS",
                "SMTP_HOST",
                "SMTP_PORT",
                "SMTP_USERNAME",
                "SMTP_PASSWORD",
                "ALERT_EMAIL_FROM",
                "ALERT_EMAIL_TO",
            ],
        ),
        (
            "Database",
            ["DATABASE_URL"],
        ),
        (
            "Scheduler",
            [
                "ENABLE_SCHEDULER",
                "SCRAPE_INTERVAL_HOURS",
                "SENATE_SCRAPE_INTERVAL_HOURS",
                "REQUEST_DELAY_SECONDS",
            ],
        ),
        (
            "Anomaly & STOCK Act Thresholds",
            [
                "ANOMALY_ALERT_THRESHOLD",
                "LARGE_TRADE_THRESHOLD",
                "STOCK_ACT_DISCLOSURE_DAYS",
            ],
        ),
    ]

    written: set[str] = set()

    for section_name, keys in sections:
        section_lines: list[str] = []
        for key in keys:
            if key in values:
                val = values[key]
                # Quote values that contain spaces or special chars
                if " " in val or "#" in val or not val:
                    val = f'"{val}"'
                section_lines.append(f"{key}={val}")
                written.add(key)
        if section_lines:
            lines.append(f"# --- {section_name} ---")
            lines.extend(section_lines)
            lines.append("")

    # Write any remaining keys not covered by sections
    remainder = [f"{k}={v}" for k, v in values.items() if k not in written]
    if remainder:
        lines.append("# --- Other ---")
        lines.extend(remainder)
        lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")


# ---------------------------------------------------------------------------
# Defaults (mirrors config.py)
# ---------------------------------------------------------------------------

DEFAULTS: dict[str, str] = {
    "ANTHROPIC_MODEL": "claude-sonnet-4-20250514",
    "DATABASE_URL": "sqlite+aiosqlite:///./congress_trades.db",
    "ENABLE_SCHEDULER": "false",
    "SCRAPE_INTERVAL_HOURS": "6",
    "SENATE_SCRAPE_INTERVAL_HOURS": "4",
    "REQUEST_DELAY_SECONDS": "1.0",
    "ANOMALY_ALERT_THRESHOLD": "50",
    "LARGE_TRADE_THRESHOLD": "100000",
    "STOCK_ACT_DISCLOSURE_DAYS": "45",
    "SMTP_PORT": "587",
    "ENABLE_EMAIL_ALERTS": "false",
}


# ---------------------------------------------------------------------------
# Main interactive flow
# ---------------------------------------------------------------------------


def run_setup(env_path: Path) -> None:
    existing = _load_existing_env(env_path)

    # Seed defaults for keys that don't already exist
    values: dict[str, str] = {**DEFAULTS, **existing}

    action = "Updating" if env_path.exists() else "Creating"
    print(f"\n{'='*60}")
    print("  Congress Trades — Environment Setup")
    print(f"  {action}: {env_path.resolve()}")
    print(f"{'='*60}")
    print("\nPress Enter to keep current values. All fields are optional")
    print("unless noted otherwise.\n")

    # ------------------------------------------------------------------
    # API Keys
    # ------------------------------------------------------------------
    print("\n[1/4] API Keys")
    print("-" * 40)

    values["ANTHROPIC_API_KEY"] = _prompt(
        "ANTHROPIC_API_KEY",
        "Used for AI-assisted PDF parsing of scanned filings.\n"
        "  Get one at: https://console.anthropic.com/",
        current=values.get("ANTHROPIC_API_KEY", ""),
        secret=True,
    )

    values["CONGRESS_API_KEY"] = _prompt(
        "CONGRESS_API_KEY",
        "Used to fetch bill/committee data from api.congress.gov.\n"
        "  Free sign-up at: https://api.congress.gov/sign-up/",
        current=values.get("CONGRESS_API_KEY", ""),
        secret=True,
    )

    # ------------------------------------------------------------------
    # Telegram
    # ------------------------------------------------------------------
    print("\n[2/4] Telegram Alerts")
    print("-" * 40)

    values["TELEGRAM_BOT_TOKEN"] = _prompt(
        "TELEGRAM_BOT_TOKEN",
        "Token for your Telegram bot.\n"
        "  Create one via @BotFather on Telegram (send /newbot).",
        current=values.get("TELEGRAM_BOT_TOKEN", ""),
        secret=True,
    )

    values["TELEGRAM_CHAT_ID"] = _prompt(
        "TELEGRAM_CHAT_ID",
        "Telegram chat/channel ID to receive alerts.\n"
        "  Find it by messaging @userinfobot on Telegram.",
        current=values.get("TELEGRAM_CHAT_ID", ""),
    )

    # ------------------------------------------------------------------
    # Email / SMTP (optional group)
    # ------------------------------------------------------------------
    print("\n[3/4] Email Alerts")
    print("-" * 40)

    want_email = _yes_no(
        "Set up email (SMTP) alerts?",
        default=values.get("ENABLE_EMAIL_ALERTS", "false").lower() == "true",
    )

    if want_email:
        values["ENABLE_EMAIL_ALERTS"] = "true"

        values["SMTP_HOST"] = _prompt(
            "SMTP_HOST",
            "SMTP server hostname (e.g. smtp.gmail.com, smtp.sendgrid.net).",
            current=values.get("SMTP_HOST", ""),
        )

        values["SMTP_PORT"] = _prompt(
            "SMTP_PORT",
            "SMTP server port (default: 587 for STARTTLS, 465 for SSL).",
            current=values.get("SMTP_PORT", "587"),
        )

        values["SMTP_USERNAME"] = _prompt(
            "SMTP_USERNAME",
            "SMTP login username (often the sender email address).",
            current=values.get("SMTP_USERNAME", ""),
        )

        values["SMTP_PASSWORD"] = _prompt(
            "SMTP_PASSWORD",
            "SMTP login password or app-specific password.",
            current=values.get("SMTP_PASSWORD", ""),
            secret=True,
        )

        values["ALERT_EMAIL_FROM"] = _prompt(
            "ALERT_EMAIL_FROM",
            "From address for outgoing alerts (e.g. alerts@yourdomain.com).",
            current=values.get("ALERT_EMAIL_FROM", ""),
        )

        values["ALERT_EMAIL_TO"] = _prompt(
            "ALERT_EMAIL_TO",
            "Comma-separated list of recipient addresses.",
            current=values.get("ALERT_EMAIL_TO", ""),
        )
    else:
        values["ENABLE_EMAIL_ALERTS"] = "false"

    # ------------------------------------------------------------------
    # Advanced / optional overrides
    # ------------------------------------------------------------------
    print("\n[4/4] Advanced Settings (press Enter to keep defaults)")
    print("-" * 40)

    if _yes_no("Customize database URL or scheduler settings?", default=False):
        values["DATABASE_URL"] = _prompt(
            "DATABASE_URL",
            "SQLAlchemy async DB URL.\n"
            "  Default: sqlite+aiosqlite:///./congress_trades.db",
            current=values.get("DATABASE_URL", DEFAULTS["DATABASE_URL"]),
        )

        values["ENABLE_SCHEDULER"] = (
            "true"
            if _yes_no(
                "Enable background scheduler (APScheduler)?",
                default=values.get("ENABLE_SCHEDULER", "false").lower() == "true",
            )
            else "false"
        )

        values["ANOMALY_ALERT_THRESHOLD"] = _prompt(
            "ANOMALY_ALERT_THRESHOLD",
            "Minimum anomaly score (0-100) to trigger an alert (default: 50).",
            current=values.get("ANOMALY_ALERT_THRESHOLD", "50"),
        )

        values["LARGE_TRADE_THRESHOLD"] = _prompt(
            "LARGE_TRADE_THRESHOLD",
            "Minimum trade amount (USD) to flag as a large trade (default: 100000).",
            current=values.get("LARGE_TRADE_THRESHOLD", "100000"),
        )

    # ------------------------------------------------------------------
    # Write
    # ------------------------------------------------------------------
    print()
    _write_env(env_path, values)

    print(f"\n  .env written to: {env_path.resolve()}")
    print("  Run `uv run python scripts/test_alerts.py --telegram` to verify alerts.")
    print()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Interactive setup for the Congress Trades .env file.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  uv run python scripts/setup_env.py\n"
            "  uv run python scripts/setup_env.py --env-file /etc/congress_trades/.env\n"
        ),
    )
    parser.add_argument(
        "--env-file",
        default=".env",
        metavar="PATH",
        help="Path to the .env file to create or update (default: .env)",
    )

    args = parser.parse_args()
    env_path = Path(args.env_file)

    # Refuse to overwrite a non-.env file accidentally
    if env_path.suffix not in (".env", "") and not env_path.name.startswith(".env"):
        print(
            f"ERROR: {env_path} does not look like a .env file. "
            "Pass --env-file explicitly if you are sure.",
            file=sys.stderr,
        )
        sys.exit(1)

    run_setup(env_path)


if __name__ == "__main__":
    main()
